"""Unit tests for the conservative local page analyzer."""

from question_bank.page_analyzer import analyze_page, analyze_pdf


class FakePage:
    def __init__(self, text: str, image_count: int = 0):
        self._text = text
        self._images = [object()] * image_count

    def extract_text(self):
        return self._text

    @property
    def images(self):
        return self._images


def test_english_question_page_is_detected():
    result = analyze_page(
        FakePage(
            "SECTION B\nQuestion numbers 7 to 10 carry 3 marks each.\n"
            "Find the height.\nFigure 1"
        ),
        5,
    )
    assert result["language"] == "english"
    assert result["question_start"] == 7
    assert result["question_end"] == 10
    assert result["is_question_page"] is True
    assert result["has_figures"] is True


def test_question_range_fallback_detects_single_question():
    result = analyze_page(FakePage("14. Find the modal age of the policy holders."), 11)
    assert result["question_start"] == 14
    assert result["question_end"] == 14
    assert result["is_question_page"] is True


def test_non_question_cover_is_not_classified_as_question_page():
    result = analyze_page(FakePage("Candidates must write the Q.P. Code on the title page."), 1)
    assert result["is_question_page"] is False


def test_adjacent_duplicate_detection_uses_same_question_range(tmp_path):
    # This is a behavior-level test using a tiny synthetic PDF generated by the
    # test suite would add a PDF dependency; the page-level behavior is covered
    # by analyze_page, while actual 11-page papers are validated manually in the
    # integration step.
    first = analyze_page(FakePage("1. (Hindi/garbled content)\n2. (Hindi/garbled content)"), 2)
    second = analyze_page(FakePage("SECTION A\nQuestion numbers 1 to 2 carry 2 marks each.\n1. Find...\n2. Solve..."), 3)
    assert first["question_start"] == 1
    assert first["question_end"] == 2
    assert second["question_start"] == 1
    assert second["question_end"] == 2
